#pragma once
#include<iostream>
#include<thread>
#include<chrono>
inline void wonderHoy() {std::cout << "Wonderhoy~!\n";}
inline void kiraKiraDokiDoki() {std::cout << "Kira kira doki doki~!\n";}
inline void Saki_Quit_Matrix(){
    std::cout << "A rainy day. Saki got wet and entered the study room.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(15000));
    std::cout << "Soyo: Saki! Great! You are here!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Soyo: Why are you soaked to the bone? Are you all right?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Soyo: You left from the study group. And never response the message.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Saki: Today I come here to say something.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Saki: Please let me quit the study group.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(6000));
    std::cout << "Soyo: Wait... Can we please sit down and talk about it?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Soyo: Why? Is everything okay?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(4000));
    std::cout << "Soyo: Can't you tell us?\n";
    std::cout << "Soyo: Or is there something we did wrong?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(4000));
    std::cout << "Soyo: If we did something wrong, we can fix it.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Saki: No, it's my problem.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Soyo: Why? Wasn't the previous activity fun and helpful?\n";
    std::cout << "Soyo: 'I want to hold the next activity!', you said so, didn't you?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Saki: I didn't say that.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Soyo: Real...Really...?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Soyo: But...,  it is you who found this study group...If you quit...\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Tomorin: Are...Are you sure?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Taki: Tomorin is asking you! This is utterly irresponsible!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Taki: Why are you not saying anything?!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Soyo: Taki, please calm down.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Taki: Do you have any idea how much trouble you are casuing us?! Today of all days -- we have all been stuck here waiting for you!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Soyo: Taki!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Saki: Even though I am not here, you still can do the study group, right?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Taki: Huh?!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Saki: If you want to continue the study group, you can do it without me.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Saki: I never ruled that everyone must be here for the study group.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Saki: Please don't blame to others.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Tomorin: But...If you quit...\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Saki: Stop saying such childish things!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Saki: Actually, you're the one who should practise more in matrix!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Saki: But what are you doing in the past?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Taki: Tomorin is waiting for you!\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Soyo: Wait! Let us sit down and talk about it. Please?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::cout << "Soyo: It should be enjoyable when we are together in practising. Mutsumi is thinking so, isn't she?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(6000));
    std::cout << "Mutsumi: I have never thought that founding the study group was a happy thing...\n";
}
inline void mafuyo(){
    std::cout << "Mafuyu: Meku... Until when can I come here?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Meku: --Until when?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(3000));
    std::cout << "Mafuyu: You said that, you want to write codes come from my real heart with me.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Mafuyu: This goal is completed, right?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Meku: Yeah.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Mafuyu: So, this project will be terminated because of it?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Meku: NO.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Mafuyu: ...Really?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Meku: The project, and these codes, all is proof of your pain, vexation and ideas.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(8000));
    std::cout << "Meku: So it will be continue, you and codes will continue to exist.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Mafuyu: ...\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Meku: Even though in one day, you forget it, the project will not disappear.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(6000));
    std::cout << "Meku: Because this is the shelter of you insight and idea.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Mafuyu: ...Although the project looks like...?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Meku: You emotions are here.\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Mafuyu: Real...Really? Even...though I disappear?\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    std::cout << "Meku: This is your own. So it will existing.\n";
}